### ISSUE TITLE
CheckSum Request

### ISSUE THREAD

**Issue by Emmanuel-Cruz** [daviswer/fewshotlocal#1]
Hello!

Trying to recreate your results on the cloud but not sure if the dataset creation is perfect. Anywho, it would be great if you included a Meta-iNat Md5 hash. Thank you! 

PS:: On windows in Train.ipynb Cell 6 Line 13 I get a pickle error somewhere deep in the in the trainloader from pytorch. Could there be an incompatibility? 

Details below: 
`
PicklingError                             Traceback (most recent call last)
<ipython-input-6-9c8d552029a3> in <module>
     11 
     12     # Train for one epoch
---> 13     trainloss, acc = train(train_loader, models, optimizer, criterion, way, shots, verbosity)
     14 
     15     # Update the graphics, report

D:\notebooks\fewshotlocal\helpful_files\training.py in train(train_loader, models, optimizer, criterion, way, shots, verbosity)
     92     acctracker = [0]*ensemble
     93     print("Training images covered this round:")
---> 94     for i, ((inp, masks), _) in enumerate(train_loader):
     95         inp = inp.cuda()
     96         masks = masks.cuda()

~\Miniconda3\lib\site-packages\torch\utils\data\dataloader.py in __iter__(self)
    191 
    192     def __iter__(self):
--> 193         return _DataLoaderIter(self)
    194 
    195     def __len__(self):

~\Miniconda3\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    467                 #     before it starts, and __del__ tries to join but will get:
    468                 #     AssertionError: can only join a started process.
--> 469                 w.start()
    470                 self.index_queues.append(index_queue)
    471                 self.workers.append(w)

~\Miniconda3\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

~\Miniconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~\Miniconda3\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

~\Miniconda3\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

~\Miniconda3\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

PicklingError: Can't pickle <function <lambda> at 0x0000020CCD20CB70>: attribute lookup <lambda> on __main__ failed`

**Comment by daviswer** [comment]
Excellent point, I'll add an md5 correctness checker to the setup notebook. As for your pickle error, it looks like pytorch is having trouble getting multithreading to work correctly on your machine. Does the code run if you set "workers" equal to 0?

**Comment by daviswer** [comment]
Added the checksum verifier

**Comment by Emmanuel-Cruz** [comment]
Thank you!

--PS: Your advice did fix the two issues I had, but another issue arose (Windows 10 PC) when running the 'Training' block in Train.ipynb. It would append a forward slash "\" to my path instead of a backward slash "/" which cause it to throw a key error in the lookup table for boxdict[path] in training.py (helpful functions). 

I fixed this by adding:
`    path = path.replace("\\", '/')
`
to the first few lines in training.py, now it all seems to work. 

Thank you again, 
-E
