### ISSUE TITLE
Covariance Pooling

### ISSUE THREAD

**Issue by Harut0726** [daviswer/fewshotlocal#4]
Will accuracy improvement still be significant if we use covariance pooling without localization? (for dataset with already cropped instances)

**Comment by daviswer** [comment]
Hello! Yes, covariance pooling should work without localization - in fact, some of our models do this already. The results table in the readme contains examples. Obviously I can't speak for your particular problem and dataset, but any task that benefits from a richer feature space should benefit from covariance pooling (i.e. 5-way 1-shot classification does not benefit, but all-way all-shot classification improves significantly).

**Comment by Harut0726** [comment]
Thank you for quick reply.
