### ISSUE TITLE
your own dataset has some probelm

### ISSUE THREAD

**Issue by ContestantsD** [daviswer/fewshotlocal#6]
all the picture in this dataset is damaged.
(https://drive.google.com/file/d/1ATRnifcZ7-_7YxXbKbCi6mL61hfk_YEJ/view?usp=sharing)

**Comment by daviswer** [comment]
Hello! Thanks for reaching out. I've re-downloaded and doublechecked the dataset images and I'm seeing no issues or damage on my side, other than the obvious fact that all images have been downsized to 84x84 resolution. Can you share the code you're using for image loading and/or visualization? For reference, the following code correctly loaded an image of a dragonfly for me:

```
from PIL import Image
from matplotlib import pyplot as plt
test = Image.open('YOUR_SAVE_PATH/meta_iNat/train/549/ffcbb8df9a27b98e3f8c59b9d1fc3e96.png')
plt.imshow(test)
```

**Comment by ContestantsD** [comment]
> Hello! Thanks for reaching out. I've re-downloaded and doublechecked the dataset images and I'm seeing no issues or damage on my side, other than the obvious fact that all images have been downsized to 84x84 resolution. Can you share the code you're using for image loading and/or visualization? For reference, the following code correctly loaded an image of a dragonfly for me:
> 
> ```
> from PIL import Image
> from matplotlib import pyplot as plt
> test = Image.open('YOUR_SAVE_PATH/meta_iNat/train/549/ffcbb8df9a27b98e3f8c59b9d1fc3e96.png')
> plt.imshow(test)
> ```

thanks for your reply. 
the images in my download meta/tiered file is damaged, but the inat2017_84x84 's file is complete, so my problem has solved.
thanks a lot !
